name: Add Namespace

on:
 workflow_dispatch
  # push:
  #   branches:
  #   - main

env:
  EKS_CLUSTER: dev
  EKS_REGION: us-east-2

jobs:
  Job1:
    name: Create namespace
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    ## AWS Credentials
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.EKS_REGION }}

    # Get the EKS credentials so we can deploy to the cluster
    - run: |-
        aws eks --region $EKS_REGION update-kubeconfig --name $EKS_CLUSTER
        
   
   # Add namespace
    - name: Add namespace
      run: |-
       kubectl create namespace donor-driver