name: Register cluster with Nirmata

on:
  workflow_dispatch

env:
  EKS_CLUSTER: dev
  EKS_REGION: us-east-2

jobs:
  Job1:
    name: Register Cluster
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    ## AWS Credentials
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.EKS_REGION }}

    # Get the EKS credentials so we can deploy to the cluster
    - run: |-
        aws eks --region $EKS_REGION update-kubeconfig --name $EKS_CLUSTER
        #kubectl config get-contexts
        #kubectl config get-contexts --no-headers | awk '{ print $2 }'
        #echo $PATH
        
   
   # Install nctl
    - name: Set up nctl
      run: |-
       curl -LO https://nirmata-downloads.s3.us-east-2.amazonaws.com/nctl/nctl_3.2.3/nctl_3.2.3_linux_64-bit.zip
       unzip nctl_3.2.3_linux_64-bit.zip
       chmod 755 nctl
       mv nctl /usr/local/bin/
       #echo $PATH
   #    nctl 
   #nctl login
  #  - name: login with token
 #     run: |-
   #    nctl clusters get --token "${{ secrets.NIRMATA_TOKEN }}"
   
   #register
    - name: Register cluster in nirmata
      run: |-
       Cluster_ARN=$(kubectl config get-contexts --no-headers | awk '{ print $2 }')
       #echo $Cluster_ARN
       #nctl cluster register  arn:aws:eks:us-east-2:860174137652:cluster/dev -f /home/runner/.kube/config -t default-addons-type -n devtest --token "${{ secrets.NIRMATA_TOKEN }}"
       nctl cluster register ${Cluster_ARN} -f /home/runner/.kube/config -t default-addons-type -n devtest --token "${{ secrets.NIRMATA_TOKEN }}"
      

